# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
      # install Checkov from pypi using pip
      pip install checkov

- script: |
      docker run --tty --volume /13_storage_blob/:/tf bridgecrew/checkov --directory /tf

- script: |

      # cd into a folder like /13_storage_blob/
      cd $(System.DefaultWorkingDirectory)/13_storage_blob/
      
      # Scan config files in current folder
      checkov -d .
      
      # Scan and output compact
      checkov -d . --compact
      
      # Scan specific file
      checkov -f main.tf --compact
      
      # Export check to json
      checkov -d . -o json